services:
  nginx:
    build: .
    # image: xanderstrike/nginx-url-shortener:latest
    ports:
      - "8080:80"
    environment:
      - ID_LENGTH=${ID_LENGTH:-5}
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/redirects:/etc/nginx/redirects
    restart: unless-stopped
